version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: todo-api-db

    environment:
      POSTGRES_DB: todo-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"