spring:
  application:
    name: todo-api

  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:postgresql://localhost:5432/todo-api
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

security:
  jwt:
    secret-key: ${JWT_SECRET:dev-only-secret-key-change-me-please-32bytes-min}
    expiration-ms: 3600000

# JAVA_HOME=$HOME/.sdkman/candidates/java/21.0.11-zulu PATH=$JAVA_HOME/bin:$PATH mvn clean instal
# docker compose up -d